<a href="https://colab.research.google.com/github/22104071/GS_071/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import tensorflow as tf

In [67]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


False

In [15]:
import pandas as pd

In [16]:
import matplotlib.pyplot as plt

In [18]:
import numpy as np

In [76]:
#Scalar
a=tf.constant(6.5)
a

<tf.Tensor: shape=(), dtype=float32, numpy=6.5>

In [22]:
#String
b=tf.constant("Gaurav")
b

<tf.Tensor: shape=(), dtype=string, numpy=b'Gaurav'>

In [75]:
#boolean tensor
c=tf.constant(True)
c

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [45]:
#Defiining a 1D array
d=tf.constant(np.array([1,2,3,4]))
d

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [44]:
#Defining a 2D array
e=tf.constant([1,2,3,4,5,6],shape=(3,2))
e

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [74]:
#Defining transpose of a tensor using a numpy array
f=tf.constant(np.transpose(e), dtype='float32')
f

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 3., 5.],
       [2., 4., 6.]], dtype=float32)>

In [107]:
#Shape of a Tensor
e.shape

TensorShape([3, 2])

In [56]:
f.shape

TensorShape([2, 3])

In [68]:
g=tf.constant([[[1,2],[2.0,3],[3,4]],[[3,4],[4,5],[5,6]]])
g

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[1., 2.],
        [2., 3.],
        [3., 4.]],

       [[3., 4.],
        [4., 5.],
        [5., 6.]]], dtype=float32)>

In [69]:
g.numpy()[1,2]

array([5., 6.], dtype=float32)

**Summary:**
A constant is a type of tensor that can store non-updatable values such as constant scalars, vectors such as list or matrices, and can store array upto n dimensions.
Its shape can be modified or can be given such as the product of values of the shape gives the total no. of elements stored in tensor.
Multiple data types such as strings, boolean, int32, float32, etc. cannot be stored in same tensor.
only float32, & int32 can be stored together.

In [72]:
#Scalar as a variable
h=tf.Variable(2)
h

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>

In [77]:
i=tf.Variable([1,2,3,4])
i

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [78]:
i.name

'Variable:0'

In [79]:
i.shape

TensorShape([4])

In [80]:
i.dtype

tf.int32

In [81]:
i.numpy()[3]

4

In [85]:
i.numpy()[2]

3

In [87]:
j=tf.Variable(2+3j)
j

<tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(2+3j)>

In [88]:
tf.Variable(d)

<tf.Variable 'Variable:0' shape=(4,) dtype=int64, numpy=array([1, 2, 3, 4])>

In [89]:
d

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 2, 3, 4])>

In [96]:
k=tf.Variable([[2,3.0],[3,6],[2,5]], shape=(3,2))
k

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[2., 3.],
       [3., 6.],
       [2., 5.]], dtype=float32)>

In [99]:
tf.reshape(k,(6,1))

<tf.Tensor: shape=(6, 1), dtype=float32, numpy=
array([[2.],
       [3.],
       [3.],
       [6.],
       [2.],
       [5.]], dtype=float32)>

In [101]:
np.max(k)

6.0

In [104]:
l=tf.convert_to_tensor(k)
l

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[2., 3.],
       [3., 6.],
       [2., 5.]], dtype=float32)>

In [119]:
#Replacing data in tensor variable
i.assign([name==1,4,6,7])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([1, 4, 6, 7], dtype=int32)>

In [122]:
#Adding a value for another memory
i.assign_add([6,8,9,0])

<tf.Variable 'UnreadVariable' shape=(4,) dtype=int32, numpy=array([ 7, 12, 15,  7], dtype=int32)>

In [127]:
i**i

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([    823543, -251658240, 1500973039,     823543], dtype=int32)>

**Summary:**
A variable is a type of tensor That can store values such as array matrices vector list etc. Which further can be assigned to a new value of the same shape and it must have the number of elements defined to the previous element want to replaced.
To assign a variable from a tensor, it has been given in above lines of code.




In [10]:
#Placeholder
#Session
import tensorflow as tf
import numpy as np
tf.compat.v1.disable_eager_execution()

In [11]:
m=tf.compat.v1.placeholder(dtype="float32",shape=(200,200))
m

<tf.Tensor 'Placeholder_2:0' shape=(200, 200) dtype=float32>

In [12]:
n=tf.compat.v1.placeholder(dtype="float32",shape=(200,200))
n

<tf.Tensor 'Placeholder_3:0' shape=(200, 200) dtype=float32>

In [13]:
c=tf.add(m,n)
c

<tf.Tensor 'Add_1:0' shape=(200, 200) dtype=float32>

In [19]:
ones_array=np.ones((200,200), np.float32)
ones_array

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

In [20]:
with tf.compat.v1.Session() as sess:
  d=sess.run(c, feed_dict={m:ones_array,n:ones_array})


In [21]:
d

array([[2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       ...,
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.],
       [2., 2., 2., ..., 2., 2., 2.]], dtype=float32)

In [22]:
type(d)

numpy.ndarray

Summary:
A placeholder is a type of tensor that can store data for furthur use.
Assumingly, it just makes a container that can store values when the tensor is called.
it is actually stored in tf version 1, so it is imported through a code, that is derived through the disabling of Eager execution.
it is use to create structure of graphs, in whuch data can be assigned in the future.


In [28]:
#Sparse Tensor
import tensorflow as tf

In [29]:
o=tf.SparseTensor(indices=[[1,2], [0,1]],values=[10,20],dense_shape=[5,10])
o
print(o)

SparseTensor(indices=tf.Tensor(
[[1 2]
 [0 1]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 5 10], shape=(2,), dtype=int64))


In [30]:
import numpy as np

In [31]:
np_array = np.array([[1,0,0,0],
                   [0,0,0,1],
                    [1,0,0,1]])
np_array

array([[1, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 1]])

In [32]:
p=tf.sparse.from_dense(np_array)
q = np.array(p)

In [33]:
print(p)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 3]
 [2 0]
 [2 3]], shape=(4, 2), dtype=int64), values=tf.Tensor([1 1 1 1], shape=(4,), dtype=int64), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


In [34]:


q

array(SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 3]
 [2 0]
 [2 3]], shape=(4, 2), dtype=int64), values=tf.Tensor([1 1 1 1], shape=(4,), dtype=int64), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)),
      dtype=object)

In [47]:
b=q.flatten().tolist()
b

[SparseTensor(indices=tf.Tensor(
 [[0 0]
  [1 3]
  [2 0]
  [2 3]], shape=(4, 2), dtype=int64), values=tf.Tensor([1 1 1 1], shape=(4,), dtype=int64), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))]